- name: Download golang binary
  get_url:
    url: "{{download_url[ansible_os_family]}}"
    dest: /tmp/golang-{{version}}.zip

- name: Ensure /usr/local is a directory
  sudo: yes
  file: path=/usr/local state=directory

- name: Extract golang binary
  sudo: yes
  unarchive:
    src: /tmp/golang-{{version}}.zip
    dest: /usr/local
    copy: no
