---
- hosts: localhost
  connection: local
  pre_tasks:
    - name: Install homebrew tap
      homebrew_tap:
        tap: "{{ item }}"
        state: present
      with_items:
        - caskroom/cask
      when: ansible_os_family == 'Darwin'
    - name: Install common packages with brew
      homebrew:
        name: "{{ item }}"
        state: latest
        update_homebrew: yes
      with_items:
        - curl
        - wget
        - python
        - mercurial
        - ansible
        - gpg
        - autojump
        - socat
        - brew-cask
        - shellcheck
      when: ansible_os_family == 'Darwin'
    - name: Install common application with casks
      homebrew_cask:
        name: "{{ item }}"
      with_items:
          - virtualbox
          - vagrant
          - boot2docker
          - google-chrome
          - firefox
          - iterm2
          - vlc
          - atom
          - sublime-text
          - sourcetree
          - google-drive
          - libreoffice
          - xquartz
      when: ansible_os_family == 'Darwin'

  roles:
    - git
    - nvm
    - oh-my-zsh
    - { role: golang, version: 1.4.2 }
    - atom
  vars:
    user_home_dir:
      Linuxmint: /home
      Darwin: /Users
