---
- name: Ensure atom config directory exists
  file:
    path: ~/.atom
    state: directory

- name: Install atom packages with apm
  apm: name={{item}} state=latest
  with_items: "{{atom_packages}}"

- name: Copy configuration files
  template:
    src: "{{item}}.j2"
    dest: "~/.atom/{{item}}"
  with_items:
    - keymap.cson
